apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        role: application
      containers:
        - name: backend
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-name
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: aws-secret-access-key
            - name: COGNITO_USER_POOL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: cognito-user-pool-id
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: cognito-client-id
