apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: { { .Values.database.host | quote } }
            - name: DB_USER
              value: { { .Values.database.user | quote } }
            - name: DB_PASSWORD
              value: { { .Values.database.password | quote } }
            - name: DB_NAME
              value: { { .Values.database.name | quote } }
            - name: AWS_REGION
              value: { { .Values.aws.region | quote } }
            - name: AWS_ACCESS_KEY_ID
              value: { { .Values.aws.accessKeyId | quote } }
            - name: AWS_SECRET_ACCESS_KEY
              value: { { .Values.aws.secretAccessKey | quote } }
            - name: COGNITO_USER_POOL_ID
              value: { { .Values.cognito.userPoolId | quote } }
            - name: COGNITO_CLIENT_ID
              value: { { .Values.cognito.clientId | quote } }
