apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # 옵션 1: nodeSelector 제거 (모든 노드에서 실행 가능)
      # 옵션 2: 클러스터에 존재하는 nodeSelector로 변경 
      # nodeSelector:
      #   role: back-node-group
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_USER
              value: "{{ .Values.database.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: AWS_REGION
              value: "{{ .Values.aws.region }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.aws.accessKeyId }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.aws.secretAccessKey }}"
            - name: COGNITO_USER_POOL
              value: "{{ .Values.cognito.userPoolId }}"
            - name: COGNITO_CLIENT_ID
              value: "{{ .Values.cognito.clientId }}"
