apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: backend
