apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # 'backend' 라벨을 가진 Pod들 대상으로 트래픽을 전달
  ports:
    - protocol: TCP
      port: 80         # 서비스 외부 포트
      targetPort: 80   # Pod의 포트
  type: ClusterIP  # 내부에서만 접근 가능하도록 ClusterIP 설정