apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3  # 3개의 백엔드 Pod 생성
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ${ECR_REPOSITORY_URI}:${VERSION_TAG}
        ports:
        - containerPort: 80
