apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  annotations:
    argocd-image-updater.argoproj.io/backend.match-tag: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend: ${ECR_REPOSITORY_URI}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: $(ECR_URI)/$(ECR_REPOSITORY):latest
        envFrom:
        - secretRef:
            name: ecr-secret
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 80
