
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AWS-Cloud-FinalProject/backend.git  # 실제 GitHub 저장소 URL로 변경
    targetRevision: v* # 또는 특정 브랜치/태그
    path: k8s/helm
    helm:
      valueFiles:
        - values.yaml  # 기본 values 파일만 참조 (민감하지 않은 정보)
      # 민감한 정보는 GitHub Actions에서 직접 Helm으로 배포할 때 values-generated.yaml로 전달됨
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # 자동 동기화 설정
  syncPolicy:
    automated:
      prune: true  # 제거된 리소스 자동 삭제
      selfHeal: true  # 수동 변경 자동 복구
    syncOptions:
      - CreateNamespace=true