apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: { { .Values.repoURL } }
    targetRevision: { { .Values.targetRevision } }
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          repository: ${ECR_REPOSITORY_URI}/webtest
          tag: ${VERSION_TAG}
          pullPolicy: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
