name: Backend CI/CD with Docker and EKS

on:
  push:
    branches:
      - production

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  version:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.generate_version.outputs.NEW_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Generate version
        id: generate_version
        run: |
          # Get the latest tag
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")

          # Extract version numbers
          MAJOR=$(echo $LATEST_TAG | sed 's/v\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/')
          MINOR=$(echo $LATEST_TAG | sed 's/v\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/')
          PATCH=$(echo $LATEST_TAG | sed 's/v\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/')

          # Get the commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Check commit message for version bump keywords
          if echo "$COMMIT_MSG" | grep -iE "BREAKING CHANGE|major" > /dev/null; then
            echo "Major version bump detected"
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif echo "$COMMIT_MSG" | grep -iE "feat|minor" > /dev/null; then
            echo "Minor version bump detected"
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            echo "Patch version bump detected"
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "Version will be: $NEW_TAG"
          echo "Commit message: $COMMIT_MSG"

      - name: Create and push Git tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -a ${{ steps.generate_version.outputs.NEW_TAG }} -m "Release ${{ steps.generate_version.outputs.NEW_TAG }}"
          git push origin ${{ steps.generate_version.outputs.NEW_TAG }}

  docker:
    needs: [build, version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          # Build and tag images
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}/backend:${{ needs.version.outputs.version_tag }} .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}/backend:${{ needs.version.outputs.version_tag }} ${{ secrets.ECR_REPOSITORY_URI }}/backend:latest

          # Push images
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/backend:${{ needs.version.outputs.version_tag }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/backend:latest

  deploy:
    needs: [docker, version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Label EKS Nodes
        run: |
          echo "Getting nodes from back-node-group..."
          NODES=$(kubectl get nodes -l eks.amazonaws.com/nodegroup=back-node-group -o jsonpath='{.items[*].metadata.name}')

          if [ -z "$NODES" ]; then
            echo "No nodes found in back-node-group"
            exit 1
          fi

          echo "Found nodes: $NODES"
          for NODE in $NODES; do
            echo "Labeling node: $NODE"
            kubectl label nodes $NODE role=back-node-group --overwrite=true
          done

          # Verify node labels
          echo "Checking node labels:"
          kubectl get nodes --show-labels | grep back-node-group

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy Applications
        run: |
          # Ensure directories exist
          mkdir -p helm/apps helm/backend

          # Create values override file for apps chart
          cat > helm/apps/values.yaml << EOF
          repoURL: https://github.com/AWS-Cloud-FinalProject/backend.git
          targetRevision: production
          backend:
            image:
              repository: "${{ secrets.ECR_REPOSITORY_URI }}/backend"
              tag: "${{ needs.version.outputs.version_tag }}"
            
            database:
              host: "${{ secrets.DB_HOST }}"
              user: "${{ secrets.DB_USER }}"
              password: "${{ secrets.DB_PASSWORD }}"
              name: "${{ secrets.DB_NAME }}"
              
            aws:
              region: "${{ secrets.AWS_REGION }}"
              accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}"
              secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              
            cognito:
              userPoolId: "${{ secrets.COGNITO_USER_POOL }}"
              clientId: "${{ secrets.COGNITO_CLIENT_ID }}"
          EOF

          # Create values file for backend chart
          cat > helm/backend/values.yaml << EOF
          replicaCount: 3
          
          image:
            repository: "${{ secrets.ECR_REPOSITORY_URI }}/backend"
            tag: "${{ needs.version.outputs.version_tag }}"
            pullPolicy: Always

          database:
            host: "${{ secrets.DB_HOST }}"
            user: "${{ secrets.DB_USER }}"
            password: "${{ secrets.DB_PASSWORD }}"
            name: "${{ secrets.DB_NAME }}"
            
          aws:
            region: "${{ secrets.AWS_REGION }}"
            accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            
          cognito:
            userPoolId: "${{ secrets.COGNITO_USER_POOL }}"
            clientId: "${{ secrets.COGNITO_CLIENT_ID }}"

          service:
            type: ClusterIP
            port: 8000
          EOF

          # Apply the apps chart using Helm with debug output
          helm upgrade --install backend-apps helm/apps -n argocd --create-namespace --debug

      - name: Cleanup old ReplicaSets
        run: |
          # Get all ReplicaSets except the latest one and delete them
          kubectl get replicaset -l app=backend -o name | tail -n +2 | xargs -r kubectl delete
